import {
  AppWindow,
  ArrowRight,
  ArrowUpRight,
  BedDouble,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Calendar,
  Check,
  Clock,
  Coffee,
  Compass,
  Download,
  ExternalLink,
  Gauge,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  Play,
  QrCode,
  Rocket,
  Rss,
  Search,
  Share2,
  ShieldCheck,
  Sparkles,
  Store,
  Target,
  UserPlus,
  Users,
  UtensilsCrossed,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const ICONS = {
  app: AppWindow,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bed: BedDouble,
  book: BookOpen,
  bot: Bot,
  brain: Brain,
  building: Building2,
  calendar: Calendar,
  check: Check,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  download: Download,
  external: ExternalLink,
  gauge: Gauge,
  globe: Globe,
  graduation: GraduationCap,
  hammer: Hammer,
  handshake: Handshake,
  layers: Layers,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  message: MessageCircle,
  phone: Phone,
  play: Play,
  qr: QrCode,
  rocket: Rocket,
  rss: Rss,
  search: Search,
  share: Share2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  store: Store,
  target: Target,
  'user-plus': UserPlus,
  users: Users,
  utensils: UtensilsCrossed,
  workflow: Workflow,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function Icon({ name, className, strokeWidth = 1.75 }: { name: IconName; className?: string; strokeWidth?: number }) {
  const Component = ICONS[name]
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" />
}
